/**
 * Mock Interview Meta Data
 * Departments and Job Roles configuration
 * FULL SYNC WITH 16-DEPT / 128-ROLE ENTERPRISE HIERARCHY
 */

const DEPARTMENTS = [
  { id: 1, name: "Human Resources (HR)", slug: "human-resources", description: "People management, recruiting, and culture.", color_hex: "#EC4899", icon_url: "users", role_count: 8 },
  { id: 2, name: "Sales & Business Development", slug: "sales-business", description: "Revenue, client acquisition, and growth.", color_hex: "#F59E0B", icon_url: "trending-up", role_count: 8 },
  { id: 3, name: "Marketing (Digital & Growth)", slug: "marketing-digital", description: "Brand, SEO, and social strategy.", color_hex: "#06B6D4", icon_url: "bar-chart", role_count: 8 },
  { id: 4, name: "Finance & FinTech", slug: "finance-fintech", description: "Accounting, fintech, and analysis.", color_hex: "#10B981", icon_url: "wallet", role_count: 8 },
  { id: 5, name: "Customer Success", slug: "customer-success", description: "Support, success, and client onboarding.", color_hex: "#8B5CF6", icon_url: "heart", role_count: 8 },
  { id: 6, name: "Operations & Business Ops", slug: "operations-ops", description: "Process, logistics, and program ops.", color_hex: "#6366F1", icon_url: "settings", role_count: 8 },
  { id: 7, name: "IT / Software", slug: "it-software", description: "Development, QA, and cloud engineering.", color_hex: "#F43F5E", icon_url: "code", role_count: 8 },
  { id: 8, name: "Data & Analytics", slug: "data-analytics", description: "Data science, BI, and analytics.", color_hex: "#14B8A6", icon_url: "database", role_count: 8 },
  { id: 9, name: "AI & Gen AI", slug: "ai-gen-ai", description: "Machine learning and prompt engineering.", color_hex: "#F97316", icon_url: "cpu", role_count: 8 },
  { id: 10, name: "Product & UX", slug: "product-ux", description: "Product management and user experience.", color_hex: "#8B5CF6", icon_url: "layout", role_count: 8 },
  { id: 11, name: "Content & Communication", slug: "content-communication", description: "Writing and communication strategy.", color_hex: "#A855F7", icon_url: "file-text", role_count: 8 },
  { id: 12, name: "Media & Creative", slug: "media-creative", description: "Design, video, and visual media.", color_hex: "#EF4444", icon_url: "camera", role_count: 8 },
  { id: 13, name: "Education & EdTech", slug: "education-edtech", description: "Training and instructional design.", color_hex: "#EAB308", icon_url: "book-open", role_count: 8 },
  { id: 14, name: "Logistics & Supply Chain", slug: "logistics-supply", description: "Supply chain and inventory management.", color_hex: "#0EA5E9", icon_url: "truck", role_count: 8 },
  { id: 15, name: "BFSI & FinTech", slug: "bfsi-fintech", description: "Banking and financial operations.", color_hex: "#3B82F6", icon_url: "briefcase", role_count: 8 },
  { id: 16, name: "Entrepreneurship / Startups", slug: "entrepreneurship-startups", description: "Venture, growth, and startup ops.", color_hex: "#6366F1", icon_url: "rocket", role_count: 8 },

  // --- CONVERSATION SCENARIOS (IDs 101 - 150) ---
  { id: 101, name: "Coffee shops", slug: "coffee-shops", description: "Practice ordering, small talk, and socializing at a café.", color_hex: "#D97706", icon_url: "cafe", role_count: 1 },
  { id: 102, name: "Restaurants", slug: "restaurants", description: "Practice ordering, asking for recommendations, and tipping.", color_hex: "#EF4444", icon_url: "restaurant", role_count: 1 },
  { id: 103, name: "Offices", slug: "offices", description: "Practice workplace introductions and watercooler chats.", color_hex: "#3B82F6", icon_url: "briefcase", role_count: 1 },
  { id: 104, name: "Colleges", slug: "colleges", description: "Practice campus interactions, asking questions, and networking.", color_hex: "#8B5CF6", icon_url: "book-open", role_count: 1 },
  { id: 105, name: "Schools", slug: "schools", description: "Practice parent-teacher discussions and school conversations.", color_hex: "#10B981", icon_url: "book-open", role_count: 1 },
  { id: 106, name: "Religious places", slug: "religious-places", description: "Practice cultural dialogues and guided tour chats.", color_hex: "#F59E0B", icon_url: "home", role_count: 1 },
  { id: 107, name: "Parks", slug: "parks", description: "Practice casual chit-chat with other walkers or dog owners.", color_hex: "#10B981", icon_url: "leaf", role_count: 1 },
  { id: 108, name: "Shopping malls", slug: "shopping-malls", description: "Practice asking for sizing, directions, and prices in a mall.", color_hex: "#EC4899", icon_url: "shopping-cart", role_count: 1 },
  { id: 109, name: "Gyms", slug: "gyms", description: "Practice talking to fitness trainers and gym members.", color_hex: "#6366F1", icon_url: "dumbbell", role_count: 1 },
  { id: 110, name: "Libraries", slug: "libraries", description: "Practice asking librarians for books and studying resources.", color_hex: "#06B6D4", icon_url: "book", role_count: 1 },
  { id: 111, name: "Public buses", slug: "public-buses", description: "Practice asking for routes, stops, and buying bus tickets.", color_hex: "#F59E0B", icon_url: "bus", role_count: 1 },
  { id: 112, name: "Train stations", slug: "train-stations", description: "Practice purchasing train tickets and asking about arrivals.", color_hex: "#3B82F6", icon_url: "train", role_count: 1 },
  { id: 113, name: "Airports", slug: "airports", description: "Practice immigration, checking in, and boarding gates talk.", color_hex: "#0EA5E9", icon_url: "plane", role_count: 1 },
  { id: 114, name: "Hotels", slug: "hotels", description: "Practice checking in, calling room service, and booking.", color_hex: "#8B5CF6", icon_url: "bed", role_count: 1 },
  { id: 115, name: "Salons", slug: "salons", description: "Practice discussing hair treatments and styling options.", color_hex: "#EC4899", icon_url: "scissors", role_count: 1 },
  { id: 116, name: "Barber shops", slug: "barber-shops", description: "Practice getting a haircut and talking with the barber.", color_hex: "#3B82F6", icon_url: "scissors", role_count: 1 },
  { id: 117, name: "Hospitals", slug: "hospitals", description: "Practice explaining symptoms to a doctor or check-in desks.", color_hex: "#EF4444", icon_url: "medkit", role_count: 1 },
  { id: 118, name: "Clinics", slug: "clinics", description: "Practice discussing checkups and booking diagnostic services.", color_hex: "#10B981", icon_url: "medkit", role_count: 1 },
  { id: 119, name: "Waiting rooms", slug: "waiting-rooms", description: "Practice breaking the ice with a stranger in a lobby.", color_hex: "#64748B", icon_url: "users", role_count: 1 },
  { id: 120, name: "Conferences", slug: "conferences", description: "Practice business networking and professional greetings.", color_hex: "#4F46E5", icon_url: "users", role_count: 1 },
  { id: 121, name: "Seminars", slug: "seminars", description: "Practice asking Q&A questions to guest speakers.", color_hex: "#8B5CF6", icon_url: "microphone", role_count: 1 },
  { id: 122, name: "Weddings", slug: "weddings", description: "Practice congratulating the couple and talking with guests.", color_hex: "#EC4899", icon_url: "heart", role_count: 1 },
  { id: 123, name: "Family gatherings", slug: "family-gatherings", description: "Practice catching up with relatives and casual chats.", color_hex: "#10B981", icon_url: "users", role_count: 1 },
  { id: 124, name: "Birthday parties", slug: "birthday-parties", description: "Practice wishing a friend and interacting with hosts.", color_hex: "#F59E0B", icon_url: "gift", role_count: 1 },
  { id: 125, name: "Sports stadiums", slug: "sports-stadiums", description: "Practice purchasing tickets and talking with fellow fans.", color_hex: "#EF4444", icon_url: "football", role_count: 1 },
  { id: 126, name: "Playgrounds", slug: "playgrounds", description: "Practice supervising kids and talking to fellow parents.", color_hex: "#10B981", icon_url: "smile", role_count: 1 },
  { id: 127, name: "Beaches", slug: "beaches", description: "Practice asking lifeguards for safe spots and instructions.", color_hex: "#06B6D4", icon_url: "sun", role_count: 1 },
  { id: 128, name: "Community centers", slug: "community-centers", description: "Practice checking class timetables and neighborhood news.", color_hex: "#6366F1", icon_url: "home", role_count: 1 },
  { id: 129, name: "Bookstores", slug: "bookstores", description: "Practice discussing recommendation and book purchases.", color_hex: "#D97706", icon_url: "book", role_count: 1 },
  { id: 130, name: "Supermarkets", slug: "supermarkets", description: "Practice billing, finding aisles, and talking to cashiers.", color_hex: "#10B981", icon_url: "shopping-cart", role_count: 1 },
  { id: 131, name: "Street corners", slug: "street-corners", description: "Practice asking local residents for quick directions.", color_hex: "#64748B", icon_url: "map", role_count: 1 },
  { id: 132, name: "Neighborhoods", slug: "neighborhoods", description: "Practice welcoming new neighbors and checking amenities.", color_hex: "#10B981", icon_url: "users", role_count: 1 },
  { id: 133, name: "Hostels", slug: "hostels", description: "Practice checking room regulations and discussing tasks.", color_hex: "#8B5CF6", icon_url: "bed", role_count: 1 },
  { id: 134, name: "Cafeterias", slug: "cafeterias", description: "Practice picking food items and requesting custom changes.", color_hex: "#D97706", icon_url: "pizza", role_count: 1 },
  { id: 135, name: "Food courts", slug: "food-courts", description: "Practice ordering combos, paying, and waiting for tokens.", color_hex: "#EF4444", icon_url: "pizza", role_count: 1 },
  { id: 136, name: "Movie theaters", slug: "movie-theaters", description: "Practice buying concessions and showing ticket stub to usher.", color_hex: "#EF4444", icon_url: "film", role_count: 1 },
  { id: 137, name: "Music concerts", slug: "music-concerts", description: "Practice talking to fans and expressing concert excitement.", color_hex: "#EC4899", icon_url: "musical-notes", role_count: 1 },
  { id: 138, name: "Festivals", slug: "festivals", description: "Practice enjoying festive displays and buying local crafts.", color_hex: "#F59E0B", icon_url: "sparkles", role_count: 1 },
  { id: 139, name: "Volunteer events", slug: "volunteer-events", description: "Practice cooperating on communal cleaning or food drives.", color_hex: "#EF4444", icon_url: "heart", role_count: 1 },
  { id: 140, name: "Co-working spaces", slug: "co-working-spaces", description: "Practice checking desk slots and introducing workspace rules.", color_hex: "#3B82F6", icon_url: "desktop", role_count: 1 },
  { id: 141, name: "Networking events", slug: "networking-events", description: "Practice elevator pitches and exchange of digital contact.", color_hex: "#4F46E5", icon_url: "users", role_count: 1 },
  { id: 142, name: "Coaching centers", slug: "coaching-centers", description: "Practice discussing batch timings and solving doubts.", color_hex: "#8B5CF6", icon_url: "book", role_count: 1 },
  { id: 143, name: "Tuition centers", slug: "tuition-centers", description: "Practice reviewing test schedules and home study progress.", color_hex: "#10B981", icon_url: "edit", role_count: 1 },
  { id: 144, name: "Online forums", slug: "online-forums", description: "Practice introducing yourself in digital developer rooms.", color_hex: "#3B82F6", icon_url: "globe", role_count: 1 },
  { id: 145, name: "Social media platforms", slug: "social-media-platforms", description: "Practice interacting with creators and commenting on blogs.", color_hex: "#0EA5E9", icon_url: "globe", role_count: 1 },
  { id: 146, name: "Gaming cafes", slug: "gaming-cafes", description: "Practice booking high-spec gaming rigs and hourly plans.", color_hex: "#6366F1", icon_url: "game-controller", role_count: 1 },
  { id: 147, name: "Podcasts", slug: "podcasts", description: "Practice answering host prompts in interview-style formats.", color_hex: "#EC4899", icon_url: "microphone", role_count: 1 },
  { id: 148, name: "Live streams", slug: "live-streams", description: "Practice requesting features or engaging live hosts in chat.", color_hex: "#EF4444", icon_url: "video", role_count: 1 },
  { id: 149, name: "WhatsApp groups", slug: "whatsapp-groups", description: "Practice sending text pitches or introducing new members.", color_hex: "#10B981", icon_url: "chatbubbles", role_count: 1 },
  { id: 150, name: "Public events", slug: "public-events", description: "Practice checking crowd entries and guided tour plans.", color_hex: "#EF4444", icon_url: "calendar", role_count: 1 }
];


const JOB_ROLES = [
  // --- 1. HUMAN RESOURCES (HR) ---
  { id: 1, department_id: 1, title: "HR Executive", slug: "hr-executive", difficulty_level: "Intermediate" },
  { id: 2, department_id: 1, title: "Recruiter", slug: "recruiter", difficulty_level: "Intermediate" },
  { id: 3, department_id: 1, title: "Talent Acquisition Associate", slug: "talent-acquisition", difficulty_level: "Intermediate" },
  { id: 4, department_id: 1, title: "HR Operations Assistant", slug: "hr-ops-assistant", difficulty_level: "Beginner" },
  { id: 5, department_id: 1, title: "HR Intern", slug: "hr-intern", difficulty_level: "Beginner" },
  { id: 6, department_id: 1, title: "People Analytics Associate", slug: "people-analytics", difficulty_level: "Advanced" },
  { id: 7, department_id: 1, title: "HR Tech Coordinator", slug: "hr-tech", difficulty_level: "Intermediate" },
  { id: 8, department_id: 1, title: "Employee Experience Executive", slug: "employee-experience", difficulty_level: "Intermediate" },

  // --- 2. SALES & BUSINESS DEVELOPMENT ---
  { id: 9, department_id: 2, title: "Sales Executive", slug: "sales-executive", difficulty_level: "Intermediate" },
  { id: 10, department_id: 2, title: "Inside Sales Rep", slug: "inside-sales", difficulty_level: "Beginner" },
  { id: 11, department_id: 2, title: "Business Development Associate", slug: "biz-dev-associate", difficulty_level: "Intermediate" },
  { id: 12, department_id: 2, title: "Lead Generation Executive", slug: "lead-gen", difficulty_level: "Beginner" },
  { id: 13, department_id: 2, title: "SaaS Sales Executive", slug: "saas-sales", difficulty_level: "Advanced" },
  { id: 14, department_id: 2, title: "Pre-Sales Executive", slug: "pre-sales", difficulty_level: "Intermediate" },
  { id: 15, department_id: 2, title: "Customer Acquisition Executive", slug: "customer-acquisition", difficulty_level: "Intermediate" },
  { id: 16, department_id: 2, title: "Growth Sales Associate", slug: "growth-sales", difficulty_level: "Intermediate" },

  // --- 3. MARKETING (DIGITAL & GROWTH) ---
  { id: 17, department_id: 3, title: "Digital Marketing Executive", slug: "digital-marketing", difficulty_level: "Intermediate" },
  { id: 18, department_id: 3, title: "Social Media Executive", slug: "social-media", difficulty_level: "Beginner" },
  { id: 19, department_id: 3, title: "SEO Executive", slug: "seo-executive", difficulty_level: "Intermediate" },
  { id: 20, department_id: 3, title: "Performance Marketing Executive", slug: "performance-marketing", difficulty_level: "Advanced" },
  { id: 21, department_id: 3, title: "Content Marketing Associate", slug: "content-marketing", difficulty_level: "Beginner" },
  { id: 22, department_id: 3, title: "Influencer Marketing Executive", slug: "influencer-marketing", difficulty_level: "Intermediate" },
  { id: 23, department_id: 3, title: "Growth Marketing Associate", slug: "growth-marketing", difficulty_level: "Intermediate" },
  { id: 24, department_id: 3, title: "Marketing Analyst", slug: "marketing-analyst", difficulty_level: "Advanced" },

  // --- 4. FINANCE & FINTECH ---
  { id: 25, department_id: 4, title: "Accounts Executive", slug: "accounts-executive", difficulty_level: "Beginner" },
  { id: 26, department_id: 4, title: "Junior Accountant", slug: "jr-accountant", difficulty_level: "Beginner" },
  { id: 27, department_id: 4, title: "Financial Analyst (Jr)", slug: "financial-analyst", difficulty_level: "Intermediate" },
  { id: 28, department_id: 4, title: "FinTech Operations Executive", slug: "fintech-ops", difficulty_level: "Intermediate" },
  { id: 29, department_id: 4, title: "Billing Executive", slug: "billing-executive", difficulty_level: "Beginner" },
  { id: 30, department_id: 4, title: "Risk Analyst (Jr)", slug: "risk-analyst", difficulty_level: "Intermediate" },
  { id: 31, department_id: 4, title: "Investment Analyst (Jr)", slug: "investment-analyst", difficulty_level: "Advanced" },
  { id: 32, department_id: 4, title: "Payroll Executive", slug: "payroll-executive", difficulty_level: "Intermediate" },

  // --- 5. CUSTOMER SUCCESS ---
  { id: 33, department_id: 5, title: "Customer Support Executive", slug: "customer-support", difficulty_level: "Beginner" },
  { id: 34, department_id: 5, title: "Customer Success Associate", slug: "customer-success", difficulty_level: "Intermediate" },
  { id: 35, department_id: 5, title: "SaaS Support Executive", slug: "saas-support", difficulty_level: "Intermediate" },
  { id: 36, department_id: 5, title: "Technical Support Associate", slug: "tech-support", difficulty_level: "Beginner" },
  { id: 37, department_id: 5, title: "Chat Support Executive", slug: "chat-support", difficulty_level: "Beginner" },
  { id: 38, department_id: 5, title: "Client Onboarding Executive", slug: "client-onboarding", difficulty_level: "Intermediate" },
  { id: 39, department_id: 5, title: "Customer Experience Associate", slug: "customer-experience", difficulty_level: "Intermediate" },
  { id: 40, department_id: 5, title: "Helpdesk Executive", slug: "helpdesk-executive", difficulty_level: "Beginner" },

  // --- 6. OPERATIONS & BUSINESS OPS ---
  { id: 41, department_id: 6, title: "Operations Executive", slug: "operations-executive", difficulty_level: "Intermediate" },
  { id: 42, department_id: 6, title: "Process Associate", slug: "process-associate", difficulty_level: "Beginner" },
  { id: 43, department_id: 6, title: "MIS Executive", slug: "mis-executive", difficulty_level: "Intermediate" },
  { id: 44, department_id: 6, title: "Business Ops Associate", slug: "business-ops", difficulty_level: "Intermediate" },
  { id: 45, department_id: 6, title: "Vendor Ops Executive", slug: "vendor-ops", difficulty_level: "Intermediate" },
  { id: 46, department_id: 6, title: "Supply Ops Executive", slug: "supply-ops", difficulty_level: "Intermediate" },
  { id: 47, department_id: 6, title: "Quality Analyst", slug: "quality-analyst", difficulty_level: "Intermediate" },
  { id: 48, department_id: 6, title: "Program Ops Associate", slug: "program-ops", difficulty_level: "Advanced" },

  // --- 7. IT / SOFTWARE ---
  { id: 49, department_id: 7, title: "Junior Software Developer", slug: "jr-software-dev", difficulty_level: "Beginner" },
  { id: 50, department_id: 7, title: "Web Developer", slug: "web-developer", difficulty_level: "Intermediate" },
  { id: 51, department_id: 7, title: "QA Tester", slug: "qa-tester", difficulty_level: "Beginner" },
  { id: 52, department_id: 7, title: "Technical Support Engineer", slug: "tech-support-engineer", difficulty_level: "Intermediate" },
  { id: 53, department_id: 7, title: "System Admin (Jr)", slug: "system-admin", difficulty_level: "Intermediate" },
  { id: 54, department_id: 7, title: "DevOps Trainee", slug: "devops-trainee", difficulty_level: "Advanced" },
  { id: 55, department_id: 7, title: "Cloud Support Associate", slug: "cloud-support", difficulty_level: "Intermediate" },
  { id: 56, department_id: 7, title: "API Support Engineer", slug: "api-support", difficulty_level: "Advanced" },

  // --- 8. DATA & ANALYTICS ---
  { id: 57, department_id: 8, title: "Data Analyst (Jr)", slug: "data-analyst", difficulty_level: "Beginner" },
  { id: 58, department_id: 8, title: "Business Analyst (Jr)", slug: "business-analyst", difficulty_level: "Intermediate" },
  { id: 59, department_id: 8, title: "Data Visualization Associate", slug: "data-viz", difficulty_level: "Intermediate" },
  { id: 60, department_id: 8, title: "BI Analyst (Jr)", slug: "bi-analyst", difficulty_level: "Intermediate" },
  { id: 61, department_id: 8, title: "Reporting Analyst", slug: "reporting-analyst", difficulty_level: "Beginner" },
  { id: 62, department_id: 8, title: "Data Quality Analyst", slug: "data-quality", difficulty_level: "Intermediate" },
  { id: 63, department_id: 8, title: "Product Analyst (Jr)", slug: "product-analyst", difficulty_level: "Intermediate" },
  { id: 64, department_id: 8, title: "Excel Analyst", slug: "excel-analyst", difficulty_level: "Beginner" },

  // --- 9. AI & GEN AI ---
  { id: 65, department_id: 9, title: "AI/ML Intern", slug: "ai-ml-intern", difficulty_level: "Beginner" },
  { id: 66, department_id: 9, title: "Gen AI Associate", slug: "gen-ai-associate", difficulty_level: "Intermediate" },
  { id: 67, department_id: 9, title: "Prompt Engineer (Jr)", slug: "prompt-engineer", difficulty_level: "Intermediate" },
  { id: 68, department_id: 9, title: "AI Chatbot Trainer", slug: "ai-chatbot-trainer", difficulty_level: "Beginner" },
  { id: 69, department_id: 9, title: "NLP Associate", slug: "nlp-associate", difficulty_level: "Advanced" },
  { id: 70, department_id: 9, title: "AI Data Trainer", slug: "ai-data-trainer", difficulty_level: "Beginner" },
  { id: 71, department_id: 9, title: "MLOps Assistant", slug: "mlops-assistant", difficulty_level: "Advanced" },
  { id: 72, department_id: 9, title: "AI Research Assistant", slug: "ai-research", difficulty_level: "Advanced" },

  // --- 10. PRODUCT & UX ---
  { id: 73, department_id: 10, title: "Product Associate", slug: "product-associate", difficulty_level: "Intermediate" },
  { id: 74, department_id: 10, title: "Product Analyst (Jr)", slug: "product-analyst-ux", difficulty_level: "Intermediate" },
  { id: 75, department_id: 10, title: "UX Writer", slug: "ux-writer", difficulty_level: "Intermediate" },
  { id: 76, department_id: 10, title: "UX Research Assistant", slug: "ux-research", difficulty_level: "Beginner" },
  { id: 77, department_id: 10, title: "UI Designer", slug: "ui-designer-product", difficulty_level: "Intermediate" },
  { id: 78, department_id: 10, title: "UX Designer (Jr)", slug: "ux-designer-jr", difficulty_level: "Beginner" },
  { id: 79, department_id: 10, title: "Product Ops Associate", slug: "product-ops", difficulty_level: "Intermediate" },
  { id: 80, department_id: 10, title: "Design Research Associate", slug: "design-research", difficulty_level: "Intermediate" },

  // --- 11. CONTENT & COMMUNICATION ---
  { id: 81, department_id: 11, title: "Content Writer", slug: "content-writer", difficulty_level: "Beginner" },
  { id: 82, department_id: 11, title: "Copywriter", slug: "copywriter", difficulty_level: "Intermediate" },
  { id: 83, department_id: 11, title: "UX Writer", slug: "ux-writer-content", difficulty_level: "Intermediate" },
  { id: 84, department_id: 11, title: "Technical Writer (Jr)", slug: "tech-writer", difficulty_level: "Intermediate" },
  { id: 85, department_id: 11, title: "Content Editor", slug: "content-editor", difficulty_level: "Intermediate" },
  { id: 86, department_id: 11, title: "Script Writer", slug: "script-writer", difficulty_level: "Intermediate" },
  { id: 87, department_id: 11, title: "SEO Content Writer", slug: "seo-content", difficulty_level: "Intermediate" },
  { id: 88, department_id: 11, title: "Communication Executive", slug: "communication-executive", difficulty_level: "Intermediate" },

  // --- 12. MEDIA & CREATIVE ---
  { id: 89, department_id: 12, title: "Graphic Designer", slug: "graphic-designer", difficulty_level: "Intermediate" },
  { id: 90, department_id: 12, title: "Video Editor", slug: "video-editor", difficulty_level: "Intermediate" },
  { id: 91, department_id: 12, title: "Motion Graphics Designer", slug: "motion-graphics", difficulty_level: "Advanced" },
  { id: 92, department_id: 12, title: "Visual Designer", slug: "visual-designer", difficulty_level: "Intermediate" },
  { id: 93, department_id: 12, title: "UI Designer", slug: "ui-designer-media", difficulty_level: "Intermediate" },
  { id: 94, department_id: 12, title: "Social Media Designer", slug: "social-media-designer", difficulty_level: "Beginner" },
  { id: 95, department_id: 12, title: "Creative Assistant", slug: "creative-assistant", difficulty_level: "Beginner" },
  { id: 96, department_id: 12, title: "Brand Design Associate", slug: "brand-design", difficulty_level: "Intermediate" },

  // --- 13. EDUCATION & EDTECH ---
  { id: 97, department_id: 13, title: "Trainer Assistant", slug: "trainer-assistant", difficulty_level: "Beginner" },
  { id: 98, department_id: 13, title: "Instructional Design Associate", slug: "instructional-design", difficulty_level: "Intermediate" },
  { id: 99, department_id: 13, title: "Academic Coordinator", slug: "academic-coordinator", difficulty_level: "Intermediate" },
  { id: 100, department_id: 13, title: "Learning Experience Designer", slug: "lx-designer", difficulty_level: "Intermediate" },
  { id: 101, department_id: 13, title: "Teaching Assistant", slug: "teaching-assistant", difficulty_level: "Beginner" },
  { id: 102, department_id: 13, title: "Program Coordinator", slug: "program-coordinator", difficulty_level: "Intermediate" },
  { id: 103, department_id: 13, title: "Curriculum Developer (Jr)", slug: "curriculum-dev", difficulty_level: "Intermediate" },
  { id: 104, department_id: 13, title: "Learning Support Executive", slug: "learning-support", difficulty_level: "Beginner" },

  // --- 14. LOGISTICS & SUPPLY CHAIN ---
  { id: 105, department_id: 14, title: "Logistics Executive", slug: "logistics-executive", difficulty_level: "Intermediate" },
  { id: 106, department_id: 14, title: "Supply Chain Coordinator", slug: "supply-chain-coord", difficulty_level: "Intermediate" },
  { id: 107, department_id: 14, title: "Inventory Executive", slug: "inventory-executive", difficulty_level: "Beginner" },
  { id: 108, department_id: 14, title: "Procurement Assistant", slug: "procurement-assistant", difficulty_level: "Beginner" },
  { id: 109, department_id: 14, title: "Dispatch Executive", slug: "dispatch-executive", difficulty_level: "Beginner" },
  { id: 110, department_id: 14, title: "Vendor Management Executive", slug: "vendor-management", difficulty_level: "Intermediate" },
  { id: 111, department_id: 14, title: "Warehouse Executive", slug: "warehouse-executive", difficulty_level: "Beginner" },
  { id: 112, department_id: 14, title: "Operations Analyst", slug: "ops-analyst-logistics", difficulty_level: "Intermediate" },

  // --- 15. BFSI & FINTECH ---
  { id: 113, department_id: 15, title: "Banking Associate", slug: "banking-associate", difficulty_level: "Beginner" },
  { id: 114, department_id: 15, title: "Relationship Executive", slug: "relationship-executive", difficulty_level: "Intermediate" },
  { id: 115, department_id: 15, title: "Loan Processing Executive", slug: "loan-processing", difficulty_level: "Beginner" },
  { id: 116, department_id: 15, title: "KYC Executive", slug: "kyc-executive", difficulty_level: "Beginner" },
  { id: 117, department_id: 15, title: "Insurance Advisor", slug: "insurance-advisor", difficulty_level: "Beginner" },
  { id: 118, department_id: 15, title: "FinTech Support Executive", slug: "fintech-support", difficulty_level: "Intermediate" },
  { id: 119, department_id: 15, title: "Credit Analyst (Jr)", slug: "credit-analyst", difficulty_level: "Advanced" },
  { id: 120, department_id: 15, title: "Wealth Management Associate", slug: "wealth-management", difficulty_level: "Advanced" },

  // --- 16. ENTREPRENEURSHIP / STARTUPS ---
  { id: 121, department_id: 16, title: "Founder’s Office Associate", slug: "founders-office", difficulty_level: "Advanced" },
  { id: 122, department_id: 16, title: "Startup Operations Executive", slug: "startup-ops", difficulty_level: "Intermediate" },
  { id: 123, department_id: 16, title: "Growth Associate", slug: "growth-associate-startup", difficulty_level: "Intermediate" },
  { id: 124, department_id: 16, title: "Product Associate", slug: "product-associate-startup", difficulty_level: "Intermediate" },
  { id: 125, department_id: 16, title: "Business Analyst (Startup)", slug: "biz-analyst-startup", difficulty_level: "Intermediate" },
  { id: 126, department_id: 16, title: "Community Manager", slug: "community-manager", difficulty_level: "Beginner" },
  { id: 127, department_id: 16, title: "Partnerships Associate", slug: "partnerships-associate", difficulty_level: "Intermediate" },
  { id: 128, department_id: 16, title: "Venture Analyst (Jr)", slug: "venture-analyst", difficulty_level: "Advanced" },

  // --- CONVERSATION ROLES (IDs 1001 - 1050) ---
  { id: 1001, department_id: 101, title: 'Barista', slug: 'barista', difficulty_level: 'Beginner' },
  { id: 1002, department_id: 102, title: 'Waiter', slug: 'waiter', difficulty_level: 'Beginner' },
  { id: 1003, department_id: 103, title: 'Office Colleague', slug: 'office-colleague', difficulty_level: 'Intermediate' },
  { id: 1004, department_id: 104, title: 'College Professor', slug: 'college-professor', difficulty_level: 'Intermediate' },
  { id: 1005, department_id: 105, title: 'School Teacher', slug: 'school-teacher', difficulty_level: 'Intermediate' },
  { id: 1006, department_id: 106, title: 'Guided Tour Coordinator', slug: 'guided-tour', difficulty_level: 'Beginner' },
  { id: 1007, department_id: 107, title: 'Fellow Park Walker', slug: 'park-walker', difficulty_level: 'Beginner' },
  { id: 1008, department_id: 108, title: 'Store Assistant', slug: 'store-assistant', difficulty_level: 'Beginner' },
  { id: 1009, department_id: 109, title: 'Personal Fitness Trainer', slug: 'personal-trainer', difficulty_level: 'Intermediate' },
  { id: 1010, department_id: 110, title: 'Librarian', slug: 'librarian', difficulty_level: 'Beginner' },
  { id: 1011, department_id: 111, title: 'Bus Conductor', slug: 'bus-conductor', difficulty_level: 'Beginner' },
  { id: 1012, department_id: 112, title: 'Ticket Clerk', slug: 'ticket-clerk', difficulty_level: 'Beginner' },
  { id: 1013, department_id: 113, title: 'Customs Officer', slug: 'customs-officer', difficulty_level: 'Intermediate' },
  { id: 1014, department_id: 114, title: 'Hotel Receptionist', slug: 'hotel-receptionist', difficulty_level: 'Intermediate' },
  { id: 1015, department_id: 115, title: 'Hair Stylist', slug: 'hair-stylist', difficulty_level: 'Beginner' },
  { id: 1016, department_id: 116, title: 'Barber', slug: 'barber', difficulty_level: 'Beginner' },
  { id: 1017, department_id: 117, title: 'Doctor', slug: 'doctor', difficulty_level: 'Intermediate' },
  { id: 1018, department_id: 118, title: 'Clinic Receptionist', slug: 'clinic-receptionist', difficulty_level: 'Beginner' },
  { id: 1019, department_id: 119, title: 'Waiting Room Stranger', slug: 'waiting-stranger', difficulty_level: 'Beginner' },
  { id: 1020, department_id: 120, title: 'Conference Attendee', slug: 'conference-attendee', difficulty_level: 'Intermediate' },
  { id: 1021, department_id: 121, title: 'Guest Speaker', slug: 'guest-speaker', difficulty_level: 'Intermediate' },
  { id: 1022, department_id: 122, title: 'Wedding Guest', slug: 'wedding-guest', difficulty_level: 'Beginner' },
  { id: 1023, department_id: 123, title: 'Catching up Uncle', slug: 'relative-uncle', difficulty_level: 'Beginner' },
  { id: 1024, department_id: 124, title: 'Party Host', slug: 'party-host', difficulty_level: 'Beginner' },
  { id: 1025, department_id: 125, title: 'Ticket Desk Assistant', slug: 'ticket-desk', difficulty_level: 'Beginner' },
  { id: 1026, department_id: 126, title: 'Supervising Parent', slug: 'another-parent', difficulty_level: 'Beginner' },
  { id: 1027, department_id: 127, title: 'Beach Lifeguard', slug: 'beach-lifeguard', difficulty_level: 'Beginner' },
  { id: 1028, department_id: 128, title: 'Community Coordinator', slug: 'community-coord', difficulty_level: 'Beginner' },
  { id: 1029, department_id: 129, title: 'Bookseller', slug: 'bookseller', difficulty_level: 'Beginner' },
  { id: 1030, department_id: 130, title: 'Supermarket Cashier', slug: 'supermarket-cashier', difficulty_level: 'Beginner' },
  { id: 1031, department_id: 131, title: 'Local Resident', slug: 'local-resident', difficulty_level: 'Beginner' },
  { id: 1032, department_id: 132, title: 'Next Door Neighbor', slug: 'next-neighbor', difficulty_level: 'Beginner' },
  { id: 1033, department_id: 133, title: 'Hostel Warden', slug: 'hostel-warden', difficulty_level: 'Intermediate' },
  { id: 1034, department_id: 134, title: 'Cafeteria Server', slug: 'cafeteria-server', difficulty_level: 'Beginner' },
  { id: 1035, department_id: 135, title: 'Food Court Counter', slug: 'food-counter', difficulty_level: 'Beginner' },
  { id: 1036, department_id: 136, title: 'Movie Theatre Usher', slug: 'theater-usher', difficulty_level: 'Beginner' },
  { id: 1037, department_id: 137, title: 'Concert Fan', slug: 'concert-fan', difficulty_level: 'Beginner' },
  { id: 1038, department_id: 138, title: 'Festival Stall Vendor', slug: 'stall-vendor', difficulty_level: 'Beginner' },
  { id: 1039, department_id: 139, title: 'Volunteer Organizer', slug: 'volunteer-organizer', difficulty_level: 'Intermediate' },
  { id: 1040, department_id: 140, title: 'Co-Working Desk Officer', slug: 'coworking-desk', difficulty_level: 'Beginner' },
  { id: 1041, department_id: 141, title: 'Professional Contact', slug: 'professional-contact', difficulty_level: 'Intermediate' },
  { id: 1042, department_id: 142, title: 'Tuition Tutor', slug: 'tuition-tutor', difficulty_level: 'Intermediate' },
  { id: 1043, department_id: 143, title: 'Reviewing Teacher', slug: 'reviewing-teacher', difficulty_level: 'Intermediate' },
  { id: 1044, department_id: 144, title: 'Forum Moderator', slug: 'forum-moderator', difficulty_level: 'Intermediate' },
  { id: 1045, department_id: 145, title: 'Digital Specialist', slug: 'digital-specialist', difficulty_level: 'Intermediate' },
  { id: 1046, department_id: 146, title: 'Gaming Cafe Owner', slug: 'cafe-owner', difficulty_level: 'Beginner' },
  { id: 1047, department_id: 147, title: 'Podcast Host', slug: 'podcast-host', difficulty_level: 'Intermediate' },
  { id: 1048, department_id: 148, title: 'Live Streamer', slug: 'live-streamer', difficulty_level: 'Intermediate' },
  { id: 1049, department_id: 149, title: 'WhatsApp Group Admin', slug: 'group-admin', difficulty_level: 'Intermediate' },
  { id: 1050, department_id: 150, title: 'Event Gate Staff', slug: 'event-staff', difficulty_level: 'Beginner' }
];

module.exports = {
  DEPARTMENTS,
  JOB_ROLES: JOB_ROLES.map(role => ({
    ...role,
    question_count: 10,
    duration_minutes: 15
  }))
};
